//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptOCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cluster
    {
        public string Cluster_ID { get; set; }
        public string Cluster_Name { get; set; }
        public string Govt_ID { get; set; }
        public string District_ID { get; set; }
        public string Village_ID { get; set; }
        public string Address { get; set; }
        public string Sector_ID { get; set; }
        public string Field_ID { get; set; }
        public string Product_ID { get; set; }
        public string Products { get; set; }
        public string MoreProducts { get; set; }
        public decimal Cluster_Lat { get; set; }
        public decimal Cluster_Long { get; set; }
        public int Cluster_EmpNumMin { get; set; }
        public int Cluster_EmpNumMax { get; set; }
        public Nullable<decimal> Cluster_EmpFemale { get; set; }
        public int Cluster_ShopNumMin { get; set; }
        public int Cluster_ShopNumMax { get; set; }
        public Nullable<decimal> OfficalProjects { get; set; }
        public Nullable<decimal> NonOfficalProjects { get; set; }
        public Nullable<decimal> CompanyPercent1 { get; set; }
        public Nullable<decimal> CompanyPercent2 { get; set; }
        public Nullable<decimal> CompanyPercent3 { get; set; }
        public Nullable<decimal> CompanyPercent4 { get; set; }
        public string ClusterNature_ID { get; set; }
        public string ClusterType_ID { get; set; }
        public string SupportingOrg { get; set; }
        public string Challenges { get; set; }
        public string MoreChallenges { get; set; }
        public string Cluster_ProductImage { get; set; }
        public string Cluster_ProcessImage { get; set; }
        public string Cluster_StudyFile1 { get; set; }
        public string Cluster_StudyFile2 { get; set; }
        public string Cluster_DetailPage1 { get; set; }
        public string Cluster_DetailPage2 { get; set; }
        public string Cluster_DetailPage3 { get; set; }
        public string MarketType_ID { get; set; }
        public string ProductSeason_ID { get; set; }
        public string ProductSeasonDetail { get; set; }
        public string ExportFlag_ID { get; set; }
        public string ExportVolume { get; set; }
        public string IncomeLevel_ID { get; set; }
        public string Income { get; set; }
        public string AdditionalInfo { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Governorate Governorate { get; set; }
        public virtual Product Product { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual District District { get; set; }
        public virtual Village Village { get; set; }
        public virtual ClusterNature ClusterNature { get; set; }
        public virtual ClusterType ClusterType { get; set; }
        public virtual ExportFlag ExportFlag { get; set; }
        public virtual IncomeLevel IncomeLevel { get; set; }
        public virtual MarketType MarketType { get; set; }
        public virtual ProductSeason ProductSeason { get; set; }
    }
}
