//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptOCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.Clusters = new HashSet<Cluster>();
            this.Products = new HashSet<Product>();
        }
    
        public string Field_ID { get; set; }
        public string Field_Name { get; set; }
        public string Sector_ID { get; set; }
    
        public virtual ICollection<Cluster> Clusters { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
