//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptOCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Governorate
    {
        public Governorate()
        {
            this.Clusters = new HashSet<Cluster>();
            this.Districts = new HashSet<District>();
            this.Villages = new HashSet<Village>();
        }
    
        public string Govt_ID { get; set; }
        public string Govt_Name { get; set; }
        public decimal Govt_Lat { get; set; }
        public decimal Govt_Long { get; set; }
    
        public virtual ICollection<Cluster> Clusters { get; set; }
        public virtual ICollection<District> Districts { get; set; }
        public virtual ICollection<Village> Villages { get; set; }
    }
}
