//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptOCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeLevel
    {
        public string IncomeLevel_ID { get; set; }
        public string IncomeLevel_Name { get; set; }
    }
}
