//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptOCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Village
    {
        public string Village_ID { get; set; }
        public string Village_Name { get; set; }
        public string Govt_ID { get; set; }
        public string District_ID { get; set; }
    
        public virtual District District { get; set; }
        public virtual Governorate Governorate { get; set; }
    }
}
